### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by GalonAquaa** [deadbushmc/Casino#2]
Coin Flip

Enter bet amount and which one, tail / head

**Comment by deadbushmc** [comment]
> 
> 
> Coin Flip
> 
> Enter bet amount and which one, tail / head

Sure will work on it

**Comment by deadbushmc** [comment]
> 
> 
> Coin Flip
> 
> Enter bet amount and which one, tail / head

Added it check -> https://github.com/deadbushmc/Casino/releases/tag/3.1 
:>
